unit TestValidation;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework,
  Validation, SysUtils, BaseTypes;

var

  FMatrixTest: TMatrix = ( // type by
    (1, 2, 3, 2, 6, 0, 7, 0, 1), // line 1
    (4, 5, 6, 0, 7, 0, 0, 9, 0), // line 2
    (7, 8, 9, 0, 0, 4, 5, 0, 0), // line 3
    (8, 2, 0, 1, 0, 0, 0, 4, 0), // line 4
    (0, 0, 4, 6, 0, 2, 9, 0, 0), // line 5
    (0, 5, 0, 0, 0, 3, 0, 2, 8), // line 6
    (0, 0, 9, 3, 0, 0, 0, 7, 4), // line 7
    (0, 0, 0, 0, 5, 0, 0, 3, 6), // line 8
    (0, 0, 0, 0, 1, 8, 0, 0, 0)); // line 9

type
  // Test methods for class TPerson
  TestTValidation = class(TTestCase)
  strict private
    FValidation: TValidation;
  protected
    procedure SetUp; override;
    procedure TearDown; override;
  public
    procedure TestCheckTileSmallFullFiled;
  end;

implementation

{ TestTPerson }

procedure TestTValidation.SetUp;
begin
  inherited;
  FValidation := FValidation.Create;
end;

procedure TestTValidation.TearDown;
begin
  inherited;
  FValidation.Destroy;
end;

procedure TestTValidation.TestCheckTileSmallFullFiled;
begin

  FValidation.CheckTileSmall(FMatrixTest,0,0);

end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTValidation.Suite);

end.
